### ISSUE TITLE
Issue with the repository .find

### ISSUE THREAD

**Issue by jgomes94** [ArsenyYankovsky/typeorm-aurora-data-api-driver#101]
**Package versions and database engine type (please complete the following information):**
 - Database Engine: mysql
 - TypeORM Version: 0.2.36
 - Driver Version 2.2.0

**Describe the bug**
Hi I'm having an issue with the .find from the getRepository it always returns me no results even though there are results to be shown. I know this is an issue with find because as soon as I try with raw sql providing a simple 'Select * from cards' I get the  correct information.

**To Reproduce**
I have the following configuration:

Docker Compose:
```
version: '3.1'

services:
  local-data-api:
    image: koxudaxi/local-data-api
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      RESOURCE_ARN: 'arn:aws:rds:us-east-1:123456789012:cluster:dummy'
      SECRET_ARN: 'arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy'
    ports:
      - "8080:80"
    networks:
      - database
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    ports:
        - "3306:3306"
    networks:
      - database
networks: 
  database:
    name: database

```
Then I have the following connection:

```
import { Connection, createConnection } from 'typeorm';
import {Card} from './entities/card'

export const getConnection = async (): Promise<Connection> => {

  const connection = await createConnection({
    type: 'aurora-data-api',
    database: 'test',
    secretArn: 'arn:aws:secretsmanager:us-east-1:123456789012:secret:dummy',
    resourceArn: 'arn:aws:rds:us-east-1:123456789012:cluster:dummy',
    region: 'eu-west-1',
    entities: [Card],
    serviceConfigOptions: {
      endpoint: 'http://local-data-api:80'
    }
  })

  return connection
}
```

This entity:

```
import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";

@Entity({name: 'cards'})
export class Card{
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  title: string;

  @Column()
  tablename: string;
}
```

and finally the code that has the problem is:
~
```
import { APIGatewayProxyResult, APIGatewayEvent } from 'aws-lambda';
import { Card } from '../database/entities/card';
import { getConnection } from '../database/db_connection'

export const lambdaHandler = async (req: APIGatewayEvent): Promise<APIGatewayProxyResult> => {
  try {
    let conn = await getConnection();
    let cardRepo = await conn.getRepository(Card);
    let res = await cardRepo.find();
    console.log('res', res); // --- returning everytime []!

    await conn.query('select * from cards'); //the strange part is that if I try with raw SQL like this it works
    
    return {"headers":{"Content-Type": "application/json", "Access-Control-Allow-Origin": "*"}, "body": JSON.stringify(res), statusCode: 200 }
  } catch (exception) {
    return { body: `{exception: ${exception.stack}}`, statusCode: 500 };
  }
};
```

The sql statements I use to create the table was this:

```
CREATE DATABASE test;

CREATE TABLE cards(
  id INT PRIMARY KEY AUTO_INCREMENT,
  tablename varchar(255),
  title varchar(255)
)
```

Any help is much appreciated, thank you!
